import {
  // Dashboard & Analytics
  mdiViewDashboard,
  mdiChartLine,
  mdiChartBar,
  mdiChartPie,
  mdiChartAreaspline,
  mdiTrendingUp,
  mdiTrendingDown,
  mdiPoll,
  mdiChartDonut,
  
  // CRM & Leads
  mdiAccount,
  mdiAccountGroup,
  mdiAccountPlus,
  mdiAccountCheck,
  mdiAccountClock,
  mdiAccountStar,
  mdiAccountHeart,
  mdiAccountCancel,
  mdiAccountConvert,
  mdiHandshake,
  mdiTarget,
  
  // WhatsApp & Comunicação
  mdiWhatsapp,
  mdiMessage,
  mdiMessageText,
  mdiMessageReply,
  mdiMessageProcessing,
  mdiPhone,
  mdiCellphone,
  mdiChat,
  mdiChatProcessing,
  mdiSend,
  mdiAttachment,
  mdiMicrophone,
  mdiVideo,
  mdiImage,
  mdiFileDocument,
  
  // Ações Gerais
  mdiPlus,
  mdiPencil,
  mdiDelete,
  mdiContentDuplicate,
  mdiEye,
  mdiEyeOff,
  mdiDownload,
  mdiUpload,
  mdiRefresh,
  mdiSync,
  mdiCheck,
  mdiClose,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowUp,
  mdiArrowDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiChevronDown,
  mdiDotsVertical,
  mdiDotsHorizontal,
  mdiFilter,
  mdiSort,
  mdiSortAscending,
  mdiSortDescending,
  mdiMagnify,
  mdiExport,
  mdiImport,
  // mdiPrint, // Não existe
  mdiPrinter,
  mdiShare,
  mdiLink,
  mdiContentCopy,
  
  // Configurações & Sistema
  mdiCog,
  mdiCogOutline,
  mdiTune,
  mdiWrench,
  mdiTools,
  mdiDatabase,
  mdiServer,
  mdiCloud,
  mdiCloudUpload,
  mdiCloudDownload,
  mdiShield,
  mdiShieldCheck,
  mdiKey,
  mdiLock,
  mdiLockOpen,
  
  // Status & Notificações
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiCloseCircle,
  mdiCloseCircleOutline,
  mdiAlertCircle,
  mdiAlertCircleOutline,
  mdiInformation,
  mdiInformationOutline,
  mdiLoading,
  mdiBell,
  mdiBellOutline,
  mdiBellRing,
  mdiAlert,
  mdiAlertDecagram,
  mdiProgressCheck,
  mdiProgressClock,
  mdiProgressDownload,
  mdiProgressUpload,
  
  // Navegação & Menu
  mdiMenu,
  mdiMenuOpen,
  mdiMenuDown,
  mdiMenuUp,
  mdiHome,
  mdiHomeOutline,
  mdiApps,
  mdiViewGrid,
  mdiViewList,
  mdiViewModule,
  mdiFullscreen,
  mdiFullscreenExit,
  mdiExpandAll,
  // mdiCollapse, // Não existe
  
  // Usuários & Perfil
  mdiAccountCircle,
  mdiAccountCircleOutline,
  mdiAccountBox,
  mdiAccountBoxOutline,
  mdiAccountMultiple,
  mdiAccountMultipleOutline,
  mdiAccountSupervisor,
  mdiAccountTie,
  mdiLogin,
  mdiLogout,
  mdiAccountKey,
  
  // Tempo & Calendário
  mdiCalendar,
  mdiCalendarOutline,
  mdiCalendarClock,
  mdiCalendarCheck,
  mdiCalendarPlus,
  mdiClock,
  mdiClockOutline,
  mdiTimer,
  mdiTimerOutline,
  mdiHistory,
  mdiUpdate,
  
  // E-commerce & Vendas
  mdiCurrencyUsd,
  mdiCash,
  mdiCashMultiple,
  mdiCreditCard,
  mdiCreditCardOutline,
  mdiCart,
  mdiCartOutline,
  mdiCartPlus,
  mdiTag,
  mdiTagOutline,
  mdiTagMultiple,
  mdiPercent,
  mdiSale,
  mdiStateMachine
} from '@mdi/js';

export const CRMIcons = {
  // Dashboard & Analytics
  dashboard: mdiViewDashboard,
  analytics: mdiChartLine, // Usando chartLine como ícone de analytics
  chartLine: mdiChartLine,
  chartBar: mdiChartBar,
  chartPie: mdiChartPie,
  chartArea: mdiChartAreaspline,
  chartDonut: mdiChartDonut,
  trending: mdiTrendingUp,
  trendingDown: mdiTrendingDown,
  poll: mdiPoll,
  
  // CRM & Leads
  lead: mdiAccount,
  leads: mdiAccountGroup,
  leadAdd: mdiAccountPlus,
  leadQualified: mdiAccountCheck,
  leadPending: mdiAccountClock,
  leadStar: mdiAccountStar,
  leadHeart: mdiAccountHeart,
  leadCancel: mdiAccountCancel,
  leadConvert: mdiAccountConvert,
  deal: mdiHandshake,
  target: mdiTarget,
  
  // WhatsApp & Comunicação
  whatsapp: mdiWhatsapp,
  message: mdiMessage,
  messageText: mdiMessageText,
  messageReply: mdiMessageReply,
  messageProcessing: mdiMessageProcessing,
  phone: mdiPhone,
  mobile: mdiCellphone,
  chat: mdiChat,
  chatProcessing: mdiChatProcessing,
  send: mdiSend,
  attachment: mdiAttachment,
  microphone: mdiMicrophone,
  video: mdiVideo,
  image: mdiImage,
  document: mdiFileDocument,
  
  // Ações Gerais
  add: mdiPlus,
  edit: mdiPencil,
  delete: mdiDelete,
  duplicate: mdiContentDuplicate,
  view: mdiEye,
  hide: mdiEyeOff,
  download: mdiDownload,
  upload: mdiUpload,
  refresh: mdiRefresh,
  sync: mdiSync,
  check: mdiCheck,
  close: mdiClose,
  arrowLeft: mdiArrowLeft,
  arrowRight: mdiArrowRight,
  arrowUp: mdiArrowUp,
  arrowDown: mdiArrowDown,
  chevronLeft: mdiChevronLeft,
  chevronRight: mdiChevronRight,
  chevronUp: mdiChevronUp,
  chevronDown: mdiChevronDown,
  dotsVertical: mdiDotsVertical,
  dotsHorizontal: mdiDotsHorizontal,
  filter: mdiFilter,
  sort: mdiSort,
  sortAsc: mdiSortAscending,
  sortDesc: mdiSortDescending,
  search: mdiMagnify,
  export: mdiExport,
  import: mdiImport,
  print: mdiPrinter,
  share: mdiShare,
  link: mdiLink,
  copy: mdiContentCopy,
  
  // Configurações & Sistema
  settings: mdiCog,
  settingsOutline: mdiCogOutline,
  tune: mdiTune,
  tools: mdiWrench,
  toolbox: mdiTools,
  database: mdiDatabase,
  server: mdiServer,
  cloud: mdiCloud,
  cloudUpload: mdiCloudUpload,
  cloudDownload: mdiCloudDownload,
  shield: mdiShield,
  shieldCheck: mdiShieldCheck,
  key: mdiKey,
  lock: mdiLock,
  unlock: mdiLockOpen,
  
  // Status & Notificações
  success: mdiCheckCircle,
  successOutline: mdiCheckCircleOutline,
  error: mdiCloseCircle,
  errorOutline: mdiCloseCircleOutline,
  warning: mdiAlertCircle,
  warningOutline: mdiAlertCircleOutline,
  info: mdiInformation,
  infoOutline: mdiInformationOutline,
  loading: mdiLoading,
  bell: mdiBell,
  bellOutline: mdiBellOutline,
  bellRing: mdiBellRing,
  alert: mdiAlert,
  alertDecagram: mdiAlertDecagram,
  progressCheck: mdiProgressCheck,
  progressClock: mdiProgressClock,
  progressDownload: mdiProgressDownload,
  progressUpload: mdiProgressUpload,
  
  // Navegação & Menu
  menu: mdiMenu,
  menuOpen: mdiMenuOpen,
  menuDown: mdiMenuDown,
  menuUp: mdiMenuUp,
  home: mdiHome,
  homeOutline: mdiHomeOutline,
  apps: mdiApps,
  grid: mdiViewGrid,
  list: mdiViewList,
  module: mdiViewModule,
  fullscreen: mdiFullscreen,
  fullscreenExit: mdiFullscreenExit,
  expand: mdiExpandAll,
  // collapse: mdiCollapse, // Não existe
  
  // Usuários & Perfil
  user: mdiAccountCircle,
  userOutline: mdiAccountCircleOutline,
  userBox: mdiAccountBox,
  userBoxOutline: mdiAccountBoxOutline,
  users: mdiAccountMultiple,
  usersOutline: mdiAccountMultipleOutline,
  supervisor: mdiAccountSupervisor,
  userTie: mdiAccountTie,
  login: mdiLogin,
  logout: mdiLogout,
  userKey: mdiAccountKey,
  
  // Tempo & Calendário
  calendar: mdiCalendar,
  calendarOutline: mdiCalendarOutline,
  calendarClock: mdiCalendarClock,
  calendarCheck: mdiCalendarCheck,
  calendarPlus: mdiCalendarPlus,
  clock: mdiClock,
  clockOutline: mdiClockOutline,
  timer: mdiTimer,
  timerOutline: mdiTimerOutline,
  history: mdiHistory,
  update: mdiUpdate,
  
  // E-commerce & Vendas
  currency: mdiCurrencyUsd,
  cash: mdiCash,
  cashMultiple: mdiCashMultiple,
  creditCard: mdiCreditCard,
  creditCardOutline: mdiCreditCardOutline,
  cart: mdiCart,
  cartOutline: mdiCartOutline,
  cartPlus: mdiCartPlus,
  tag: mdiTag,
  tagOutline: mdiTagOutline,
  tagMultiple: mdiTagMultiple,
  percent: mdiPercent,
  sale: mdiSale,
  automation: mdiStateMachine
};

export default CRMIcons;

